# Generated by Django 5.2.6 on 2025-09-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='media/', verbose_name='fayl yuklash')),
                ('summary', models.TextField(verbose_name='Faylga izoh bering...')),
            ],
        ),
    ]
