# Generated by Django 5.2.6 on 2025-09-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programms',
            name='category',
            field=models.CharField(choices=[('antivirus', 'Antivirus'), ('os', 'Operating System'), ('other', 'Boshqa')], default='other', max_length=20),
        ),
    ]
