# Generated by Django 5.2.6 on 2025-09-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_programms_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programms',
            name='document',
        ),
        migrations.AddField(
            model_name='programms',
            name='download_link',
            field=models.URLField(blank=True, null=True, verbose_name='Yuklab olish uchun URL'),
        ),
        migrations.AddField(
            model_name='programms',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='rasm yuklash'),
        ),
        migrations.AlterField(
            model_name='programms',
            name='category',
            field=models.CharField(choices=[('antivirus', 'Antivirus'), ('os', 'Operatsion sistema'), ('mobile', 'Mobil dastur')], default='other', max_length=20),
        ),
    ]
