# Generated by Django 5.2.6 on 2025-09-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_programms_document_programms_download_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programms',
            name='category',
            field=models.CharField(choices=[('antivirus', 'Antivirus'), ('os', 'Operatsion sistema'), ('mobile', 'Mobil dastur'), ('other', 'Boshqa')], default='other', max_length=20),
        ),
    ]
