# Generated by Django 5.2.6 on 2025-10-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_programms_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programms',
            name='category',
            field=models.CharField(choices=[('antivirus', 'Antivirus'), ('os', 'Operatsion sistema'), ('mobile', 'Mobil dastur'), ('comp', 'Kompyuter dasturi'), ('other', 'Boshqa')], default='other', max_length=20),
        ),
    ]
