# Generated by Django 5.2.6 on 2025-10-08 06:19

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_programms_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programms',
            name='summary',
            field=tinymce.models.HTMLField(),
        ),
    ]
